### ISSUE TITLE
Usage question

### ISSUE THREAD

**Issue by aledbf** [rochdev/datadog-tracer-js#6]
Hi, I'm trying to use this module but I only get ` cannot PUT /v0.3/traces (400)` errors.
Is there a particular agent version or configured required? (besides enabling the apm module)
Thanks

**Comment by rochdev** [comment]
What version are you using? `0.1` had a major issue and was generating an invalid payload. Try updating to the latest version and this should no longer happen.

Usually if the agent is not configured properly you would receive a `2xx` or `5xx` error. A `4xx` error definitely comes from the library.

**Comment by rochdev** [comment]
@aledbf Did updating to the latest version resolve your issue?

**Comment by aledbf** [comment]
@rochdev I installed from the git repo

**Comment by rochdev** [comment]
Installing directly from the git repo is not supported. Updating to the latest version using `npm` or `yarn` should resolve the issue.

Let me know if it doesn't and I will reopen the issue.
